name: "Check Branch Name"
description: "Verify that branch pushed satisfy naming convention"
inputs:
   type:
      description: "Type check" # 'release', 'main'
      required: true
      default: "release"
outputs:
   branch:
      description: "Normalized branch name"
      value: ${{ steps.normalize-branch-name.outputs.result }}
runs:
   using: "composite"
   steps:
      - uses: actions/checkout@v2

      - name: Check input
        uses: actions/github-script@v5
        with:
           script: |
              const params = ["release", "main"];
              if (!params.includes("${{ inputs.type }}")) {
                 throw new Error("Invalid input: 'release' or 'main'.");
                 process.exit(1);
              }

      - name: Target
        run: echo "The target branch name is ${{ github.event.pull_request.base.ref }}"

      - name: Verify release push
        if: ${{ inputs.type == 'release' }}
        uses: actions/github-script@v5
        with:
           script: |
              const originBranch = "${{ github.head_ref }}";
              const regexp = /^(feature|hotfix|bugfix|experimental)\/(issue-[0-9]+)$/g;
              const matches = originBranch.match(regexp);

              if (!matches) {
                 throw new Error("You only can push from [feature/hotfix/bugfix/experimental] branch to release/**");
                 process.exit(1);
              }

      - name: Verify main push
        if: ${{ inputs.type == 'main' }}
        uses: actions/github-script@v5
        with:
           script: |
              const originBranch = "${{ github.head_ref }}";
              const regexp = /^(release)\/([0-9]\.[0-9]\.[0-9])$/g;
              const matches = originBranch.match(regexp);

              if (!matches) {
                 throw new Error("You only can push from release/** branch to main");
                 process.exit(1);
              }

      - id: normalize-branch-name
        uses: actions/github-script@v5
        with:
           result-encoding: string
           script: |
              const originBranch = "${{ github.head_ref }}";
              return originBranch.replace(/\./g, "-").replace(/\//g, "-");
