name: "Jest"
description: "Run unit testing with Jest"
runs:
   using: "composite"
   steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
           node-version: "16.13.0"

      - name: Configure Pnpm Cache
        uses: actions/cache@v2
        with:
           path: ~/.pnpm-store
           key: ${{ runner.os }}-node16-${{ hashFiles('**/package.json') }}
           restore-keys: ${{ runner.os }}-node16-

      - name: Install Pnpm and Dependencies
        uses: pnpm/action-setup@v2.0.1
        with:
           version: 6.22.2
           run_install: true

      - name: Run Unit Testing
        run: pnpm test

      - name: Save Unit Testing Coverage Reports
        uses: actions/upload-artifact@v2
        with:
           name: unit-testing-report
           path: dist/jest/coverage

      - name: Save Unit Testing Coverage LCOV
        uses: actions/upload-artifact@v2
        with:
           name: unit-testing-report-lcov
           path: dist/jest/coverage/lcov.info
