#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check first if we are pushing to protected
BRANCH="$(git branch --show-current)"

if [ "$SKIP_CHECK" == "true" ]; then
   echo "CAUTION: Skipping pre-push hook"
else
   # Run Jest tests with coverage
   pnpm test

   # Run Playwright local E2E tests
   pnpm e2e
   pnpm e2e-storybook
fi
