#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

BRANCH="$(git branch --show-current)"

if [ "$SKIP_CHECK" == "true" ]; then
   echo "CAUTION: Skipping pre-commit hook"
else
   if [ "$BRANCH" == "main" ]; then
      echo "ERROR: You can't commit to protected main"
      exit 1
   fi

   # Lint github/workflows yaml files
   sh "$PWD"/tools/scripts/linter/yaml.sh

   pnpm lint
   pnpm format

   # Add changes to commit
   git add .
fi
