name: Analysis, Unit Testing & E2E Testing
on:
   pull_request:
      types: [opened, synchronize, reopened]
      branches:
         - main
         - staging
         - development
jobs:
   analysis:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
           with:
              fetch-depth: 0
         - name: Scan
           uses: SonarSource/sonarcloud-github-action@master
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

   lint:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2

         - uses: actions/setup-node@v2
           with:
              node-version: "14.18.1"

         - uses: pnpm/action-setup@v2.0.1
           with:
              version: 6.22.2
              run_install: true

         - name: Build app
           run: pnpm build

         - name: Run lint
           run: pnpm lint

   unit-testing:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2

         - uses: actions/setup-node@v2
           with:
              node-version: "14.18.1"

         - uses: pnpm/action-setup@v2.0.1
           with:
              version: 6.22.2
              run_install: true

         - name: Run tests
           run: pnpm test -- --coverage

         - name: Copy dist coverage
           run: cp dist/tests/unit/reports tools/images/unit-tests/build/

         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v1

         - name: Login to DockerHub
           uses: docker/login-action@v1
           with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

         - name: Get the version
           id: get_version
           run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
           # :${{ steps.get_version.outputs.VERSION }}

         - name: Build and push
           uses: docker/build-push-action@v2
           with:
              context: ./tools/images/unit-tests/build
              push: true
              tags: caenguidanos/caenguidanos-io-unit-testing/${{ git.ref }}:latest

   e2e-testing:
      runs-on: ubuntu-latest
      env:
         GITHUB_CI: true
      steps:
         - uses: actions/checkout@v2

         - uses: actions/setup-node@v2
           with:
              node-version: "14.18.1"

         - uses: pnpm/action-setup@v2.0.1
           with:
              version: 6.22.2
              run_install: true

         - name: Install operating system dependencies
           run: pnpx playwright install-deps webkit chrome firefox chromium

         - name: Install browsers
           run: pnpx playwright install webkit chrome firefox chromium

         - name: Build app
           run: pnpm build

         - name: Run tests
           run: pnpm playwright -- test --config=test/e2e/config/ci/playwright.config.ts
           env:
              PLAYWRIGHT_BASE_URL: "https://caenguidanos-io.vercel.app/"
              # TODO: Get preview URL from Vercel

         - name: Copy dist coverage
           run: cp dist/tests/e2e/ci tools/images/e2e-tests/build/

         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v1

         - name: Login to DockerHub
           uses: docker/login-action@v1
           with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

         - name: Build and push
           uses: docker/build-push-action@v2
           with:
              context: ./tools/images/e2e-tests/build
              push: true
              tags: caenguidanos/caenguidanos-io-e2e-testing/${{ git.ref }}:latest
