name: Analysis, Unit Testing & E2E Testing
on:
   pull_request:
      types: [opened, synchronize, reopened]
      branches:
         - main
         - staging
         - development
jobs:
   prepare:
      runs-on: ubuntu-latest
      steps:
         - name: Print branch name
           run: echo "The branch name is ${{ github.event.pull_request.base.ref }}"

   lint:
      runs-on: ubuntu-latest
      needs: [prepare]
      steps:
         - uses: actions/checkout@v2

         - uses: actions/setup-node@v2
           with:
              node-version: "14.18.1"

         - uses: pnpm/action-setup@v2.0.1
           with:
              version: 6.22.2
              run_install: true

         - name: Build app
           run: pnpm build

         - name: Run lint
           run: pnpm lint

   analysis:
      runs-on: ubuntu-latest
      needs: [prepare]
      steps:
         - uses: actions/checkout@v2
           with:
              fetch-depth: 0
         - name: Scan
           uses: SonarSource/sonarcloud-github-action@master
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

   unit-testing:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2

         - uses: actions/setup-node@v2
           with:
              node-version: "14.18.1"

         - uses: pnpm/action-setup@v2.0.1
           with:
              version: 6.22.2
              run_install: true

         - name: Run tests
           run: pnpm test -- --coverage

         - name: Archive code coverage results
           uses: actions/upload-artifact@v2
           with:
              name: unit-test-report
              path: dist/tests/unit/reports

   deploy:
      needs: [analysis, lint, unit-testing]
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2

         - uses: actions/setup-node@v2
           with:
              node-version: "14.18.1"

         - uses: pnpm/action-setup@v2.0.1
           with:
              version: 6.22.2
              run_install: false

         - name: Install Vercel CLI
           run: pnpm i -g vercel

         - name: Deploy
           if:  ${{ github.event.pull_request.base.ref == 'development' }}
           run: |
              VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }}
              VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }}

              vercel -C -S ${{ secrets.VERCEL_SCOPE }} -t ${{ secrets.VERCEL_TOKEN }} > _.txt

         - name: Deploy staging
           if:  ${{ github.event.pull_request.base.ref == 'staging' }}
           run: |
              VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }}
              VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }}

              vercel -C -S ${{ secrets.VERCEL_SCOPE }} -t ${{ secrets.VERCEL_TOKEN }} > _.txt

         - name: Deploy production
           if:  ${{ github.event.pull_request.base.ref == 'main' }}
           run: |
              VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }}
              VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }}

              vercel -C --prod -S ${{ secrets.VERCEL_SCOPE }} -t ${{ secrets.VERCEL_TOKEN }} > _.txt

         - uses: actions/github-script@v5
           with:
             result-encoding: string
             script: |
               const { readFileSync } = require('fs');
               const { join } = require('path');

               console.log(JSON.stringify({
                    context,
                    github,
                    content,
                    pw: ${{ $PWD }}
                 }, undefined, 3));

               try {
                 const root = process.cwd();
                 const file = join(root, '_.txt');

                 const content = readFileSync(file, 'utf-8');

                 console.log({ content });
               } catch (err) {
                 console.error(err)
               }

               return "https://caenguidanos-io.vercel.app";

         - name: Get preview url
           run:  echo "preview_url=${{ steps.read-stdout.outputs.result }}" >> $GITHUB_ENV

         - name: Archive preview url
           uses: actions/upload-artifact@v2
           with:
              name: preview-url
              path: _.txt

   e2e-testing-linux:
      needs: [deploy]
      runs-on: ubuntu-latest
      env:
         GITHUB_CI: true
      steps:
         - uses: actions/checkout@v2

         - uses: actions/setup-node@v2
           with:
              node-version: "14.18.1"

         - uses: pnpm/action-setup@v2.0.1
           with:
              version: 6.22.2
              run_install: true

         - name: Install operating system dependencies
           run: pnpx playwright install-deps webkit chrome firefox

         - name: Install browsers
           run: pnpx playwright install webkit chrome firefox

         - name: Build app
           run: pnpm build

         - name: Run tests
           run: pnpm playwright -- test --config=e2e/config/ci/playwright.config.ts
           env:
              PLAYWRIGHT_BASE_URL: ${{ env.preview_url }}

         - name: Archive code coverage results
           uses: actions/upload-artifact@v2
           with:
              name: e2e-test-report-linux
              path: dist/tests/e2e/reports

   e2e-testing-windows:
      needs: [deploy]
      runs-on: windows-latest
      env:
         GITHUB_CI: true
      steps:
         - uses: actions/checkout@v2

         - uses: actions/setup-node@v2
           with:
              node-version: "14.18.1"

         - uses: pnpm/action-setup@v2.0.1
           with:
              version: 6.22.2
              run_install: true

         - name: Install operating system dependencies
           run: pnpx playwright install-deps webkit chrome firefox

         - name: Install browsers
           run: pnpx playwright install webkit chrome firefox

         - name: Build app
           run: pnpm build

         - name: Run tests
           run: pnpm playwright -- test --config=e2e/config/ci/playwright.config.ts
           env:
              PLAYWRIGHT_BASE_URL: ${{ env.preview_url }}

         - name: Archive code coverage results
           uses: actions/upload-artifact@v2
           with:
              name: e2e-test-report-windows
              path: dist/tests/e2e/reports

   e2e-testing-macos:
      needs: [deploy]
      runs-on: macos-latest
      env:
         GITHUB_CI: true
      steps:
         - uses: actions/checkout@v2

         - uses: actions/setup-node@v2
           with:
              node-version: "14.18.1"

         - uses: pnpm/action-setup@v2.0.1
           with:
              version: 6.22.2
              run_install: true

         - name: Install operating system dependencies
           run: pnpx playwright install-deps webkit chrome firefox

         - name: Install browsers
           run: pnpx playwright install webkit chrome firefox

         - name: Build app
           run: pnpm build

         - name: Run tests
           run: pnpm playwright -- test --config=e2e/config/ci/playwright.config.ts
           env:
              PLAYWRIGHT_BASE_URL: ${{ env.preview_url }}

         - name: Archive code coverage results
           uses: actions/upload-artifact@v2
           with:
              name: e2e-test-report-macos
              path: dist/tests/e2e/reports