name: CI/CD
on:
   pull_request:
      types: [opened, synchronize, reopened]
      branches:
         - main
         - staging
         - development
jobs:
   prepare:
      runs-on: ubuntu-latest
      steps:
         - name: Print branch name
           run: echo "The branch name is ${{ github.event.pull_request.base.ref }}"

   lint:
      runs-on: ubuntu-latest
      needs: [prepare]
      steps:
         - uses: actions/checkout@v2

         - uses: actions/setup-node@v2
           with:
              node-version: "14.18.1"

         - uses: actions/cache@v2
           with:
              path: ~/.pnpm-store
              key: ${{ runner.os }}-node14-${{ hashFiles('**/package.json') }}
              restore-keys: ${{ runner.os }}-node14-

         - uses: pnpm/action-setup@v2.0.1
           with:
              version: 6.22.2
              run_install: true

         - name: Build app
           run: pnpm build

         - name: Run lint
           run: pnpm lint

   analysis:
      runs-on: ubuntu-latest
      needs: [prepare]
      steps:
         - uses: actions/checkout@v2
           with:
              fetch-depth: 0
         - name: Scan
           uses: SonarSource/sonarcloud-github-action@master
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

   unit-testing:
      runs-on: ubuntu-latest
      needs: [lint]
      steps:
         - uses: actions/checkout@v2

         - uses: actions/setup-node@v2
           with:
              node-version: "14.18.1"

         - uses: actions/cache@v2
           with:
              path: ~/.pnpm-store
              key: ${{ runner.os }}-node14-${{ hashFiles('**/package.json') }}
              restore-keys: ${{ runner.os }}-node14-

         - uses: pnpm/action-setup@v2.0.1
           with:
              version: 6.22.2
              run_install: true

         - name: Run tests
           run: pnpm test -- --coverage

         - name: Archive code coverage results
           uses: actions/upload-artifact@v2
           with:
              name: unit-test-report
              path: dist/tests/unit/reports

   deploy:
      needs: [lint, unit-testing]
      runs-on: ubuntu-latest
      outputs:
         url: ${{ steps.vercel-deploy.outputs.PREVIEW_URL }}
      steps:
         - uses: actions/checkout@v2

         - uses: actions/setup-node@v2
           with:
              node-version: "14.18.1"

         - uses: actions/cache@v2
           with:
              path: ~/.pnpm-store
              key: ${{ runner.os }}-node14-${{ hashFiles('**/package.json') }}
              restore-keys: ${{ runner.os }}-node14-

         - uses: pnpm/action-setup@v2.0.1
           with:
              version: 6.22.2
              run_install: false

         - name: Deploy
           id: vercel-deploy
           run: |
              if [[ "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
                production="--prod"
              fi

              pnpx vercel -t ${VERCEL_TOKEN} $production > deployment.txt

              url=$(cat deployment.txt)
              echo "::set-output name=PREVIEW_URL::$url"
           env:
              VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
              VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
              VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

         - name: Archive preview url
           uses: actions/upload-artifact@v2
           with:
              name: preview-url
              path: deployment.txt

   e2e-testing:
      needs: [deploy]
      runs-on: ubuntu-latest
      env:
         GITHUB_CI: true
      steps:
         - uses: actions/checkout@v2

         - uses: actions/setup-node@v2
           with:
              node-version: "14.18.1"

         - uses: actions/cache@v2
           with:
              path: ~/.pnpm-store
              key: ${{ runner.os }}-node14-${{ hashFiles('**/package.json') }}
              restore-keys: ${{ runner.os }}-node14-

         - uses: pnpm/action-setup@v2.0.1
           with:
              version: 6.22.2
              run_install: false

         - name: Install operating system dependencies
           run: pnpx playwright install-deps

         - name: Install browsers
           run: pnpx playwright install

         - name: Run tests
           run: pnpx playwright test --config=e2e/config/ci/playwright.config.ts
           env:
              PLAYWRIGHT_BASE_URL: ${{ needs.deploy.outputs.url }}

         - name: Archive code coverage results
           uses: actions/upload-artifact@v2
           with:
              name: e2e-testing-report
              path: dist/tests/e2e/reports/ci
