name: CI/CD
on: [push]
jobs:
   unit-testing:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: "14.18.1"
        - uses: pnpm/action-setup@v2.0.1
          with:
            version: 6.22.2
            run_install: true
        - name: Run Jest
          run: pnpm test:coverage
   e2e-testing:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: "14.18.1"
        - uses: pnpm/action-setup@v2.0.1
          with:
            version: 6.22.2
            run_install: true
        - name: Install operating system dependencies
          run: pnpx playwright install-deps chromium chrome firefox webkit
        - name: Install browsers
          run: pnpx playwright install chromium chrome firefox webkit
        - name: Run E2E tests
          run: pnpm e2e:ci
          env:
            PLAYWRIGHT_BASE_URL: "https://caenguidanos-io.vercel.app"