name: CI/CD
on: [push]
jobs:
   unit-testing:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
           with:
              node-version: "14.18.1"
        - uses: pnpm/action-setup@v2.0.1
          with:
            version: 6.22.2
            run_install: true
        - name: Run Jest
          run: pnpm test:coverage
        - name: Install Vercel cli
          run: pnpm i -g vercel
        - name: Deploy coverage Jest
          run: chmod +x ./config/deploy/vercel.coverage.sh && ./config/deploy/vercel.coverage.sh 
          env:
            VERCEL_SCOPE: "caenguidanos"
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_JEST }}
   e2e-testing:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
           with:
              node-version: "14.18.1"
        - uses: pnpm/action-setup@v2.0.1
          with:
            version: 6.22.2
            run_install: true
        - name: Install operating system dependencies
          run: pnpx playwright install-deps chromium chrome msedge firefox
        - name: Install browsers
          run: pnpx playwright install chromium chrome msedge firefox
        - name: Run E2E tests
          run: pnpm e2e:ci
          env:
            PLAYWRIGHT_BASE_URL: "https://caenguidanos-io.vercel.app"
        - name: Install Vercel cli
          run: pnpm i -g vercel
        - name: Deploy coverage E2E
          run: chmod +x ./config/deploy/vercel.coverage-e2e.sh && ./config/deploy/vercel.coverage-e2e.sh 
          env:
            VERCEL_SCOPE: "caenguidanos"
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_E2E }}