on:
   pull_request:
      types: [closed]
      branches:
         - main
name: CI/CD Production
env:
   GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT }}
   GCP_REGION: ${{ secrets.GCP_REGION }}
   GCP_ARTIFACT_REPOSITORY: ${{ secrets.GCP_ARTIFACT_REPOSITORY }}
jobs:
   unit-testing:
      runs-on: ubuntu-latest
      if: github.event.pull_request.merged == true
      env:
         GCP_CLOUD_RUN_SERVICE: unit-jest-reports
      steps:
         - name: Unit run
           uses: ./.github/actions/unit-testing

         - name: Unit deploy
           uses: ./.github/actions/e2e-testing-deploy.yaml
           with:
              key: ${{ secrets.GCP_SA_KEY }}
              region: ${{ env.GCP_REGION }}
              service: ${{ env.GCP_CLOUD_RUN_SERVICE }}
              image: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_ARTIFACT_REPOSITORY }}/${{ env.GCP_CLOUD_RUN_SERVICE }}:${{ github.sha }}

   deploy-preview:
      needs: [unit-testing]
      runs-on: ubuntu-latest
      if: github.event.pull_request.merged == true
      steps:
         - name: Vercel deployment
           uses: ./.github/actions/deploy.yaml

   e2e-testing:
      needs: [deploy]
      runs-on: ubuntu-latest
      if: github.event.pull_request.merged == true
      env:
         GCP_CLOUD_RUN_SERVICE: e2e-playwright-reports
      steps:
         - name: E2E Run
           uses: ./.github/actions/e2e-testing.yaml

         - name: E2E Deploy
           uses: ./.github/actions/e2e-testing-deploy.yaml
           with:
              key: ${{ secrets.GCP_SA_KEY }}
              region: ${{ env.GCP_REGION }}
              service: ${{ env.GCP_CLOUD_RUN_SERVICE }}
              image: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_ARTIFACT_REPOSITORY }}/${{ env.GCP_CLOUD_RUN_SERVICE }}:${{ github.sha }}

   deploy-production:
      needs: [e2e-testing]
      runs-on: ubuntu-latest
      if: github.event.pull_request.merged == true
      steps:
         - name: Vercel deployment
           uses: ./.github/actions/deploy-production.yaml
