on:
   pull_request:
      types: [opened, synchronize, reopened]
      branches:
         - release/**
name: CI/CD
jobs:
   prepare:
      runs-on: ubuntu-latest
      steps:
         - name: Check Branch
           uses: ./.github/actions/check-branch-name
           with:
              type: release

   unit-testing:
      runs-on: ubuntu-latest
      needs: [prepare]
      steps:
         - name: Run unit tests
           uses: ./.github/actions/unit-testing

   deploy:
      needs: [unit-testing]
      runs-on: ubuntu-latest
      steps:
         - name: Run deploy
           uses: ./.github/actions/deploy

   e2e-testing:
      needs: [deploy]
      runs-on: ubuntu-latest
      steps:
         - name: Run e2e tests
           uses: ./.github/actions/e2e-testing
