name: CI/CD
on: [push]
jobs:
   runs-on: ubuntu-latest
   steps:
      generate_coverage_reports:
         - uses: actions/checkout@v2
         - uses: pnpm/action-setup@v2.0.1
           with:
              version: 6.22.2
              run_install: true
         - name: Run Jest tests
           run: pnpm test:coverage
         - name: Build app
           run: pnpm build
         - name: Install operating system dependencies for E2E
           run: pnpx playwright install-deps
         - name: Run E2E tests
           run: pnpm e2e:ci
           env:
              PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
      deploy_coverage_reports:
         - name: Install vercel cli
           run: pnpm i -g vercel
         - name: Deploy coverage E2E
           run: ./config/deploy/vercel.coverage-e2e.sh
           env:
              VERCEL_SCOPE: "caenguidanos"
              VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
              VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
              VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_E2E }}
         - name: Deploy coverage Jest
           run: ./config/deploy/vercel.coverage-e2e.sh
           env:
              VERCEL_SCOPE: "caenguidanos"
              VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
              VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
              VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_JEST }}
