name: CI/CD
on: [push]
jobs:
   coverage-reports:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v2
           with:
              node-version: "14.18.1"
         - name: Install deps
           run: npm install
         - name: Install operating system dependencies for E2E
           run: npx playwright install-deps chromium
         - name: Run Jest tests
           run: npm test:coverage
         - name: Build app
           run: npm build
         - name: Run E2E tests
           run: npm e2e:ci
           env:
              PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
         - name: Install vercel cli
           run: npm i -g vercel
         - name: Deploy coverage E2E
           run: ./config/deploy/vercel.coverage-e2e.sh
           env:
              VERCEL_SCOPE: "caenguidanos"
              VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
              VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
              VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_E2E }}
         - name: Deploy coverage Jest
           run: ./config/deploy/vercel.coverage-e2e.sh
           env:
              VERCEL_SCOPE: "caenguidanos"
              VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
              VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
              VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_JEST }}
