name: CI/CD
on: [push]
jobs:
   generate_and_deploy_coverage_reports:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v2
           with:
              node-version: "14.18.1"
         - uses: pnpm/action-setup@v2.0.1
           with:
              version: 6.22.2
         - name: Show info
           run: echo ${{ github.event.deployment_status.target_url }} && echo ${{ github.event.deployment_status.state }}
         - name: Install deps
           run: pnpm install
         - name: Run Jest tests
           run: pnpm test:coverage
         - name: Build app
           run: pnpm build
         - name: Install operating system dependencies for E2E
           run: npx playwright install-deps
         - name: Run E2E tests
           run: pnpm e2e:ci
           env:
              PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
         - name: Install vercel cli
           run: pnpm i -g vercel
         - name: Deploy coverage E2E
           run: ./config/deploy/vercel.coverage-e2e.sh
           env:
              VERCEL_SCOPE: "caenguidanos"
              VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
              VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
              VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_E2E }}
         - name: Deploy coverage Jest
           run: ./config/deploy/vercel.coverage-e2e.sh
           env:
              VERCEL_SCOPE: "caenguidanos"
              VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
              VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
              VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_JEST }}
