name: E2E Testing
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
   playwright:
      runs-on: ubuntu-latest
      env:
        GITHUB_CI: true
      steps:
        - uses: actions/checkout@v2

        - uses: actions/setup-node@v2
          with:
            node-version: "14.18.1"

        - uses: pnpm/action-setup@v2.0.1
          with:
            version: 6.22.2
            run_install: true

        - name: Install operating system dependencies
          run: pnpx playwright install-deps webkit chrome firefox chromium

        - name: Install browsers
          run: pnpx playwright install webkit chrome firefox chromium

        - name: Build app
          run: pnpm build

        - name: Run tests
          run: pnpm playwright -- test --config=test/e2e/config/ci/playwright.config.ts
          env:
            PLAYWRIGHT_BASE_URL: "https://caenguidanos-io.vercel.app"

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./test/e2e/reports
            push: true
            tags: caenguidanos/caenguidanos-io-e2e-testing:latest
            build-args: |
              REPORT=ci
           