name: E2E Testing
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
   playwright:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: "14.18.1"
        - uses: pnpm/action-setup@v2.0.1
          with:
            version: 6.22.2
            run_install: true
        - name: Install operating system dependencies
          run: pnpx playwright install-deps webkit chrome firefox
        - name: Install browsers
          run: pnpx playwright install webkit chrome firefox
        - name: Run tests
          run: pnpm playwright -- test --config=test/e2e/config/ci/playwright.config.ts
          env:
            PLAYWRIGHT_BASE_URL: "https://caenguidanos-io.vercel.app"
        - name: Install os utils
          run: sudo apt-get install zip unzip
        - name: Pack report
          run: zip -r test/e2e/deploy/ci.zip test/e2e/reports/ci
        - name: switching from HTTPS to SSH
          run: git remote set-url origin ${{ secrets.ssh }}
        - name: check for changes
          run: git status
        - name: stage changed files
          run: git add test/e2e/deploy/ci.zip
        - name: commit changed files
          run: git commit -m "Auto updating e2e-reporter" --no-verify
        - name: fetch from master
          run: git fetch origin main
        - name: push code to master
          run: git push origin HEAD:main