name: Unit Testing
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
   jest:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - uses: actions/setup-node@v2
          with:
            node-version: "14.18.1"

        - uses: pnpm/action-setup@v2.0.1
          with:
            version: 6.22.2
            run_install: true
  
        - name: Run tests
          run: pnpm test:coverage

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./test/unit/reports
            push: true
            tags: caenguidanos/caenguidanos-io-unit:latest