name: Unit Testing
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
   jest:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: "14.18.1"
        - uses: pnpm/action-setup@v2.0.1
          with:
            version: 6.22.2
            run_install: true
        - name: Run Jest
          run: pnpm test:coverage